apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: '{{ .Values.aws.iam.nodeRole }}'
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-x86_64-standard-1.33-*"
  subnetSelectorTerms:
    - tags:
        SubnetType: "private"
        karpenter.sh/discovery: '{{ .Values.aws.eks.clusterName }}'
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: '{{ .Values.aws.eks.clusterName }}'